config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'about' => 'pages#about' #creates about_path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	# :default_url => "/images/img.png", image incase an image is missing
	has_attached_file :image, :styles => {:small => "200x200", :medium => "300x300", :thumb=> "100x100" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates :image, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
  validates :password, length: { in: 6..20 }

  has_many :pins, dependent: :destroy

  def name_initialed
  	split = name.split(" ")
  	newsplit = split[1]
  	lastName = newsplit[0] + "."

  	fullName = split[0] + " " + lastName
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
 	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  
  def index
    @pins = Pin.all.order("created_at DESC")
  end


  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

      if @pin.save
       redirect_to @pin, notice: 'Drink was successfully created.'
      else
       render :new 
      end
  end

  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Drink was successfully updated.'
      else
        render :edit 
      end
  end

  def destroy
    @pin.destroy
      redirect_to pins_url, notice: 'Drink was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end
 
    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this drink!" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :locale)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/time_helper.rb
module TimeHelper 
	def hours_until_happy_hour
		egg = Time.now.strftime("%k")
		egg
	end

	def seconds_until_happy_hour
		
	end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        drinksphere.
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!-- Left Hand Links -->
    <!--   <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
 -->      
      <!-- Search Form -->
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
          <li>
            <!--
            <%= link_to new_pin_path, class: "strong" do %>
              <i class="fa fa-plus"></i>
              New Drink
              <% end %>
            -->
          </li> 
        <% if user_signed_in? %>
          <li><%= link_to edit_user_registration_path do %>
             <i class="fa fa-gears">&nbsp;</i>
             Account Settings
          <% end %>
          </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>drinksphere.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag '//use.typekit.net/bxr4hlq.js' %>
  <%= javascript_tag 'try{Typekit.load();}catch(e){}' %> 
  <%= favicon_link_tag 'https://s3.amazonaws.com/drinksphere/favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


  
    <%= render 'layouts/header' %>
    <%= content_for :fluidity %>
    <div class="container top-buffer">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are are working on our One Month Rails Pinteresting app!</p>

app/views/pages/home.html.erb
<div class="hero center">
      <h1 class="boom">Evolved Social Drinking</h1>
      <h2 class="badoom">Discover new favorites.</h2>
      <!-- Sign up / Sign in buttons if user not signed in -->
      <% if !user_signed_in? %>
    
          <%= link_to new_user_registration_path do%>
            <div class="cta-sign">Sign Up</div>
          <% end %>
      
      <% end %>

    </div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Title" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
 <div class="form-group">
   <%= f.label :locale %>
   <%= f.text_field :locale, class: "form-control" %>
 </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<%= link_to 'Back', pins_path %>
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> &nbsp;

app/views/pins/index.html.erb
<% content_for :fluidity do %>
  <div class="hero center">
        <h1 class="boom">Social Drink Discovery</h1>
        <h2 class="badoom">Find your next favorite <div id="drinking_buddy">drink.</div></h2>
        <!-- Sign up / Sign in buttons if user not signed in -->
        <% unless user_signed_in? %>
      
          <%= link_to new_user_registration_path do%>
            <div class="cta-sign">Sign Up</div>
          <% end %>
          <% else %>
          <ul class="dash-container">
            <li class="dash">
              <i class="fa fa-facebook"> &nbsp;SHARE</i>
            </li>
            <li class="dash">
              <i class="fa fa-twitter"> &nbsp;TWEET</i>
            </li>
          </ul>

        <% end %>
        
  </div>
<% end %>
<ul class="mini-nav">
  <!-- <li><h4><%= Pin.count %> Drinks</h4></li> -->
 <li> <%= link_to new_pin_path, class: "strong" do %>
       <i class="fa fa-plus"></i>
       New Drink
   <% end %>
 </li>
 <li>
   My Feed
 </li>
 <li>
   Most Popular
 </li>
 <li>
   Local Favorites
 </li> 
 <li>
   
 </li>
</ul>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
          <%= link_to image_tag(pin.image.url(:medium)), pin%>
          <div class="panel-body boxxer">
            <%= pin.description %>
            <br />
            <% if pin.locale%>
              <div class="locale"><i class="fa fa-map-marker">&nbsp;</i><%= pin.locale %></div>
            <% end %>
              
              <div class="actions">
              <div class="name"><%= pin.user.name_initialed if pin.user %></div>
              <% if pin.user == current_user %>
                <%= link_to edit_pin_path(pin) do %>
                  <i class="fa fa-pencil-square-o right-buffer"></i>
                <% end %>
                <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-times"></i>
                <% end %>
              <% end %>
            </div>
          </div>
          
    </div>
  <% end %>
</div>

<br>

app/views/pins/new.html.erb
<h1>New Drink</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p>
          <%= @pin.description %>
        </p>
        <p>
          <div class="locale">
            <% if @pin.locale %>
              <i class="fa fa-map-marker">&nbsp;</i><%= @pin.locale %>
            <% end %>
          </div>
        </p>
        <div class="actions">
              <div class="name"><%= @pin.user.name_initialed %></div>
              <% if @pin.user == current_user %>
                <%= link_to edit_pin_path(@pin) do %>
                  <i class="fa fa-pencil-square-o right-buffer"></i>
                <% end %>
                <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-times"></i>
                <% end %>
              <% end %>
            </div>
      </div>

    </div>
    
  </div>
</div>